steps:
  - name: "bhgedigital/envsubst"
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        /usr/bin/envsubst < .env.$BRANCH_NAME.tmp > .env.production
        /usr/bin/envsubst < k8s/deployment.tmp.yaml > k8s/deployment.yaml
        /usr/bin/envsubst < k8s/service.tmp.yaml > k8s/service.yaml
    env:
    - 'COMMIT=$COMMIT_SHA'
    - 'BRANCH_NAME=$BRANCH_NAME'

  # Verify
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cat .env.production
        cat k8s/deployment.yaml
        cat k8s/service.yaml

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--file=Dockerfile_production', '--tag=gcr.io/fis-us/frontend:${COMMIT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fis-us/frontend:${COMMIT_SHA}']

  # kubectl apply
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cluster-1 --zone europe-west1-b --project fis-us
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-west1-b
      - CLOUDSDK_CONTAINER_CLUSTER=cluster-1

  # kubectl rollout status
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cluster-1 --zone europe-west1-b --project fis-us
        kubectl rollout status deployment.apps/frontend-$BRANCH_NAME -n app
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-west1-b
      - CLOUDSDK_CONTAINER_CLUSTER=cluster-1
    
timeout: 600s
