apiVersion: v1
kind: Service
metadata:
  name: frontend-$BRANCH_NAME
  namespace: app
spec:
  type: NodePort
  selector:
    app: frontend-$BRANCH_NAME
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: frontend
